DEFINE USER_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE EXEL_TABLE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    Project_Name VARCHAR2(300),
    Project_Description VARCHAR2(300),
    Project_Start_Date DATE,
    Project_End_Date DATE,
    Stage_Name VARCHAR2(300),
    Stage_Start_Date DATE,
    Stage_End_Date DATE,
    Stage_Tasks_Code VARCHAR2(300),
    Stage_Tasks_Start_Date DATE,
    Stage_Tasks_End_Date DATE,
    Stage_Tasks_Name VARCHAR2(300),
    Stage_Tasks_Status VARCHAR2(300),
    Assigned_Person_Name VARCHAR2(300),
    Assigned_Person_Last_Name VARCHAR2(300),
    Assigned_Person_Position VARCHAR2(300),
    Assigned_Person_Department VARCHAR2(300),
    Team_Lead_Name VARCHAR2(300),
    Team_Lead_Last_Name VARCHAR2(300)
) TABLESPACE &&1&&CURS;

INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Планирование',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('01-03-2019', 'DD/MM/YYYY'),'PLA-001',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('15-01-2019', 'DD/MM/YYYY'),'Проектирование планирования','Выполнена','Волчик','Владислав','Project Manager','Management',' ',' ');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Планирование',TO_DATE('01-02-2019', 'DD/MM/YYYY'),TO_DATE('01-03-2019', 'DD/MM/YYYY'),'PLA-002',TO_DATE('15-01-2019', 'DD/MM/YYYY'),TO_DATE('01-02-2019','DD/MM/YYYY'),'Разработка планирования','Выполнена','Илья','Шапиро','Scrum Master','Management',' ',' ');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Планирование',TO_DATE('01-02-2019', 'DD/MM/YYYY'),TO_DATE('01-03-2019', 'DD/MM/YYYY'),'PLA-003',TO_DATE('01-02-2019', 'DD/MM/YYYY'),TO_DATE('01-03-2019', 'DD/MM/YYYY'),'Реализация','Выполнена','Гутько','Антон','Architect','Development',' ',' ');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Дизайн',TO_DATE('01-02-2019', 'DD/MM/YYYY'),TO_DATE('01-04-2019', 'DD/MM/YYYY'),'DIS-001',TO_DATE('01-02-2019', 'DD/MM/YYYY'),TO_DATE('15-02-2019', 'DD/MM/YYYY'), 'Проектирование Дизайна','Проектирование','Игнат','Фомин','Developer','Development','Дмитрий','Куделич');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Дизайн',TO_DATE('01-02-2019', 'DD/MM/YYYY'),TO_DATE('01-04-2019', 'DD/MM/YYYY'),'DIS-002',TO_DATE('15-02-2019', 'DD/MM/YYYY'),TO_DATE('15-03-2019', 'DD/MM/YYYY'),'Разработка Дизайна','Разработка','Анатолий','Агейчик','Developer','Development','Дмитрий','Куделич');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Дизайн',TO_DATE('01-02-2019', 'DD/MM/YYYY'),TO_DATE('01-04-2019', 'DD/MM/YYYY'),'DIS-003',TO_DATE('15-03-2019', 'DD/MM/YYYY'),TO_DATE('01-04-2019', 'DD/MM/YYYY'),'Реализация решения','Реализация','Игнат','Фомин','Developer','Development','Дмитрий','Куделич');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Разработка',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'DEV-001',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-04-2019', 'DD/MM/YYYY'),'Задача 1','Отменена','Дмитрий','Куделич','DEV Team Lead','Development',' ',' ');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Разработка',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'DEV-001',TO_DATE('01-04-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2019', 'DD/MM/YYYY'),'Задача 2','Выполнена','Игнат','Фомин','Developer','Development','Дмитрий','Куделич');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Разработка',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'DEV-002',TO_DATE('01-05-2019', 'DD/MM/YYYY'),TO_DATE('01-06-2019', 'DD/MM/YYYY'),'Задача 3','Выполнена','Анатолий','Агейчик','Developer','Development','Дмитрий','Куделич');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Разработка',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'DEV-003',TO_DATE('01-06-2019', 'DD/MM/YYYY'),TO_DATE('01-07-2019', 'DD/MM/YYYY'),'Задача 4','Выполнена','Игнат','Фомин','Developer','Development','Дмитрий','Куделич');

INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Разработка',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'DEV-004',TO_DATE('01-07-2019', 'DD/MM/YYYY'),TO_DATE('01-08-2019', 'DD/MM/YYYY'),'Задача 5','Выполняется','Анатолий','Агейчик','Developer','Development','Дмитрий','Куделич');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Разработка',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'DEV-005',TO_DATE('01-08-2019', 'DD/MM/YYYY'),TO_DATE('01-09-2019', 'DD/MM/YYYY'),'Задача 6','Выполняется','Денис','Мартиневский','DEV Team Lead','Development',' ',' ');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Разработка',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'DEV-006',TO_DATE('01-09-2019', 'DD/MM/YYYY'),TO_DATE('01-10-2019', 'DD/MM/YYYY'),'Задача 7','Выполняется','Алексей','Тухолко','Developer','Development','Денис','Мартиневский');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Разработка',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'DEV-007',TO_DATE('01-10-2019', 'DD/MM/YYYY'),TO_DATE('01-11-2019', 'DD/MM/YYYY'),'Задача 8','Готова к тестированию','Роман','Жилко','Developer','Development','Денис','Мартиневский');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Разработка',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'DEV-008',TO_DATE('01-11-2019', 'DD/MM/YYYY'),TO_DATE('01-12-2019', 'DD/MM/YYYY'),'Задача 9','Заморожена','Алексей','Тухолко','Developer','Development','Денис','Мартиневский');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Разработка',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'DEV-009',TO_DATE('01-12-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'Задача 10','Готова к выполнению','Роман','Жилко','Developer','Development','Денис','Мартиневский');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Тестирование',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'TST-001',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-09-2019', 'DD/MM/YYYY'),'Тестирование задачи 1','Тестируется','Константин','Збойчик','QA Team Lead','Testing',' ',' ');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Тестирование',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'TST-002',TO_DATE('01-09-2019', 'DD/MM/YYYY'),TO_DATE('20-04-2019', 'DD/MM/YYYY'),'Тестирование задачи 2','Выполняется','Фаррухшох','Бобоев','Tester','Testing','Константин','Збойчик');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Тестирование',TO_DATE('01-03-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'TST-003',TO_DATE('20-04-2019', 'DD/MM/YYYY'),TO_DATE('01-05-2020', 'DD/MM/YYYY'),'Тестирование задачи 3','Выполнена','Фаррухшох','Бобоев','Tester','Testing','Константин','Збойчик');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Поддержка',TO_DATE('01-08-2019', 'DD/MM/YYYY'),TO_DATE('01-01-2023', 'DD/MM/YYYY'),'SUP-001',TO_DATE('01-08-2019', 'DD/MM/YYYY'),TO_DATE('01-09-2019', 'DD/MM/YYYY'),'Проектирование подддержки','Проектирование','Гапанович','Евгений','SUP Team Lead','Support Department',' ',' ');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Поддержка',TO_DATE('01-08-2019', 'DD/MM/YYYY'),TO_DATE('01-01-2023', 'DD/MM/YYYY'),'SUP-002',TO_DATE('01-09-2019', 'DD/MM/YYYY'),TO_DATE('01-01-2023', 'DD/MM/YYYY'),'Поддержка','Готова к выполнению','Марченко','Иван','Support Engineer','Support Department','Гапанович','Евгений');
INSERT INTO EXEL_TABLE(Project_Name,Project_Description,Project_Start_Date,Project_End_Date,Stage_Name,Stage_Start_Date,Stage_End_Date,Stage_Tasks_Code,Stage_Tasks_Start_Date,Stage_Tasks_End_Date,Stage_Tasks_Name,Stage_Tasks_Status,Assigned_Person_Name,Assigned_Person_Last_Name,Assigned_Person_Position,Assigned_Person_Department,Team_Lead_Name,Team_Lead_Last_Name) VALUES('Global Ticket','Продажа билетов по всему миру',TO_DATE('01-01-2019', 'DD/MM/YYYY'),TO_DATE('07-04-2021', 'DD/MM/YYYY'),'Поддержка',TO_DATE('01-08-2019', 'DD/MM/YYYY'),TO_DATE('01-01-2023', 'DD/MM/YYYY'),'SUP-003',TO_DATE('01-08-2019', 'DD/MM/YYYY'),TO_DATE('01-09-2019', 'DD/MM/YYYY'),'Формирование команды','Выполнена','Ильин','Александр','Support Engineer','Support Department','Гапанович','Евгений');