-- DEPARTMENT INSERT
INSERT INTO DEPARTMENT(NAME,FLOOR,DESCRIPTION) 
SELECT  DISTINCT EXEL_TABLE.Assigned_person_department,1,null FROM EXEL_TABLE;


-- ROLE INSERT
INSERT INTO ROLE(ROLE_NAME) 
SELECT DISTINCT Assigned_Person_Position FROM EXEL_TABLE;

-- COMPATIBILITY TABLE 
INSERT INTO compatibility_table (id_role,id_incompatible_role)
select role.id,1 from role order by id asc;

-- PROJECT INSERT
INSERT INTO PROJECT(NAME,DESCRIPTION,START_DAY,END_DAY)
SELECT  DISTINCT
        PROJECT_NAME AS NAME, 
        PROJECT_DESCRIPTION AS DESCEND,     
        PROJECT_START_DATE AS STARTD, 
        PROJECT_END_DATE AS ENDD
        FROM EXEL_TABLE; 

--STATUS INSERT
INSERT INTO STATUS(STATUS_NAME)
select distinct STAGE_TASKS_STATUS from EXEL_TABLE;

-- EMPLOYEE INSERT
INSERT INTO EMPLOYEE(NAME,SURNAME,DEPARTMENT_ID)
SELECT DISTINCT 
    ASSIGNED_PERSON_NAME NAME, 
    ASSIGNED_PERSON_LAST_NAME AS SURNAME,
    DEPARTMENT.ID DP_ID
    FROM EXEL_TABLE T1
    INNER join DEPARTMENT
    on DEPARTMENT.NAME = T1.ASSIGNED_PERSON_DEPARTMENT;
   
  --TEAM INSERT
  
   INSERT INTO TEAM(EMPLOYEE_LEAD_ID)
  SELECT DISTINCT
        T1.ID
        FROM EMPLOYEE T1
        INNER JOIN EXEL_TABLE T2
        ON T1.NAME = T2.TEAM_LEAD_NAME AND T1.SURNAME = T2.TEAM_LEAD_LAST_NAME;
       
--STAGE INSERT
INSERT INTO STAGE(NAME,STAGE_START_DATE,STAGE_END_DATE,PROJECT_ID)
SELECT DISTINCT STAGE_NAME,STAGE_START_DATE,STAGE_END_DATE,PROJECT.ID
FROM EXEL_TABLE
INNER JOIN PROJECT ON EXEL_TABLE.PROJECT_NAME=PROJECT.NAME;    

 --EMPLOYEE PROJECT INSERT    
INSERT INTO EMPLOYEE_PROJECT(EMPLOYEE_ID,PROJECT_ID)
SELECT DISTINCT EMPLOYEE.ID,PROJECT.ID
FROM EMPLOYEE
INNER JOIN EXEL_TABLE ON EXEL_TABLE.ASSIGNED_PERSON_NAME=EMPLOYEE.NAME
INNER JOIN PROJECT ON PROJECT.NAME=EXEL_TABLE.PROJECT_NAME;

-- TASK INSERT
INSERT INTO TASK(NAME,STATUS_ID,START_DATE,END_DATE,STAGE_ID)
SELECT DISTINCT STAGE_TASKS_NAME,STATUS.ID STATUS,STAGE_TASKS_START_DATE,STAGE_TASKS_END_DATE,STAGE.ID STAGE
FROM EXEL_TABLE 
INNER JOIN STATUS on STATUS.STATUS_NAME=EXEL_TABLE.STAGE_TASKS_STATUS
INNER JOIN STAGE ON STAGE.NAME=EXEL_TABLE.STAGE_NAME AND stage.stage_start_date=EXEL_TABLE.STAGE_START_DATE
ORDER BY STAGE_TASKS_START_DATE,STAGE_TASKS_END_DATE;

--EMPLOYEE TAST INSERT
INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID,TASK_ID)
SELECT DISTINCT EMPLOYEE.ID,TASK.ID
FROM TASK
INNER JOIN EXEL_TABLE 
on EXEL_TABLE.STAGE_TASKS_NAME=TASK.NAME
INNER JOIN EMPLOYEE
ON EXEL_TABLE.ASSIGNED_PERSON_NAME=EMPLOYEE.NAME;

INSERT INTO SKILLS(SKILL_NAME) VALUES ('PYTHON');
INSERT INTO SKILLS(SKILL_NAME) VALUES ('JAVA');
INSERT INTO SKILLS(SKILL_NAME) VALUES ('TSQL');
 
 -- EMPLOYEE ROLE INSERT
INSERT INTO EMPLOYEE_ROLE(EMPLOYEE_ID, ROLE_ID)
SELECT  DISTINCT EMPLOYEE.ID, ROLE.ID 
FROM EMPLOYEE
INNER JOIN EXEL_TABLE on EMPLOYEE.NAME=exel_table.assigned_person_name
INNER JOIN ROLE on EXEL_TABLE.Assigned_Person_Position=ROLE.ROLE_NAME;
