PROMPT 'START CREATE TableSpaces'
DEFINE USER_NAME = &&1
DEFINE TBS_LOCATION =  &&2
DEFINE DATA = '_DATA'
DEFINE IDX='_IDX'
DEFINE PAR = '.dbf'

CREATE SMALLFILE TABLESPACE &&USER_NAME&DATA
DATAFILE '&&TBS_LOCATION\&&USER_NAME&DATA&PAR'
SIZE 10M AUTOEXTEND ON NEXT 10M
MAXSIZE 5120M EXTENT MANAGEMENT LOCAL SEGMENT SPACE 
MANAGEMENT AUTO;


CREATE SMALLFILE TABLESPACE &&USER_NAME&IDX
DATAFILE '&&TBS_LOCATION\&&USER_NAME&IDX&PAR'
SIZE 10M AUTOEXTEND ON NEXT 10M
MAXSIZE 5120M EXTENT MANAGEMENT LOCAL SEGMENT SPACE 
MANAGEMENT AUTO;


PROMPT 'TableSpaces CREATED'