PROMPT 'Drop TableSpaces'

DEFINE USER_NAME = &&1
DEFINE DATA = '_DATA'
DEFINE IDX='_IDX'

DROP TABLESPACE &&USER_NAME&&DATA
  INCLUDING CONTENTS
    CASCADE CONSTRAINTS;
    

DROP TABLESPACE &&USER_NAME&&IDX
  INCLUDING CONTENTS
    CASCADE CONSTRAINTS;
    
PROMPT 'TableSpaces Dropped'