DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE STATUS (
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, STATUS_NAME VARCHAR2(100) 
) TABLESPACE &&DATA_TBS_NAME&&CURS;

COMMENT ON COLUMN STATUS.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN STATUS.STATUS_NAME IS 'Name of status';
