CREATE TABLE EMPLOYEE_PROJECT (
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, ID_PERSON NUMBER 
, ID_PROJECT NUMBER 
);
COMMENT ON COLUMN EMPLOYEE_PROJECT.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN EMPLOYEE_PROJECT.ID_PERSON IS 'Number of Person';

COMMENT ON COLUMN EMPLOYEE_PROJECT.ID_PROJECT IS 'Number of Project';
