DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE EMPLOYEE_ROLE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    EMPLOYEE_ID NUMBER,
    ROLE_ID NUMBER
) TABLESPACE &&DATA_TBS_NAME&&CURS;

COMMENT ON COLUMN EMPLOYEE_ROLE.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN EMPLOYEE_ROLE.EMPLOYEE_ID IS 'Number of role';

COMMENT ON COLUMN EMPLOYEE_ROLE.EMPLOYEE_ID IS 'Number of person';