DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE SKILLS (
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, SKILL_NAME VARCHAR2(100) 
) TABLESPACE &&DATA_TBS_NAME&&CURS;

COMMENT ON COLUMN SKILLS.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN SKILLS.SKILL_NAME IS 'Skill name';
