CREATE TABLE EMPLOYEE_ROLE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
    ID_PERSON NUMBER,
     ID_ROLE NUMBER
);


COMMENT ON COLUMN EMPLOYEE_ROLE.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN EMPLOYEE_ROLE.ID_ROLE IS 'Number of role';

COMMENT ON COLUMN EMPLOYEE_ROLE.ID_PERSON IS 'Number of person';