CREATE TABLE TASK (
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, ID_TASK NUMBER 
, ID_PROJECT NUMBER 
, DESCRIPTION VARCHAR2(100) 
, ID_STATUS NUMBER 
, ID_TEAM NUMBER 
);

COMMENT ON COLUMN TASK.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN TASK.ID_TASK IS 'Number of task';

COMMENT ON COLUMN TASK.ID_PROJECT IS 'Number of project';

COMMENT ON COLUMN TASK.DESCRIPTION IS 'Description of task';

COMMENT ON COLUMN TASK.ID_TEAM IS 'Number of team';
