DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE STAGE (
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, NAME VARCHAR2(100)
, STAGE_START_DATE DATE
, STAGE_END_DATE DATE
, PROJECT_ID NUMBER
) TABLESPACE &&DATA_TBS_NAME&&CURS;

COMMENT ON COLUMN STAGE.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN STAGE.NAME IS 'Name of this stage';

COMMENT ON COLUMN STAGE.STAGE_START_DATE IS 'START DATE FOR THE STAGE';

COMMENT ON COLUMN STAGE.STAGE_END_DATE IS 'END DATE FOR THE STAGE';

COMMENT ON COLUMN STAGE.PROJECT_ID IS 'Fk for project ';

