CREATE TABLE SKILL_EMPLOYEE 
(
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, ID_PERSON NUMBER 
, ID_SKILL NUMBER 
);


COMMENT ON COLUMN SKILL_EMPLOYEE.ID_PERSON IS 'Unique number for person';

COMMENT ON COLUMN SKILL_EMPLOYEE.ID_SKILL IS 'Number of skill';
