CREATE TABLE EMPLOYEE 
(
ID_PERSON NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, ID_PROJECT NUMBER 
, ID_DEPARTMENT NUMBER 
, ID_TEAM NUMBER 
, NAME VARCHAR2(100) 
, SURNAME VARCHAR2(100) 
, EMAIL VARCHAR2(100) 
, PHONE VARCHAR2(100) 
, ADRESS VARCHAR2(100) 
);

COMMENT ON COLUMN EMPLOYEE.ID_PROJECT IS 'Number of Project';

COMMENT ON COLUMN EMPLOYEE.ID_DEPARTMENT IS 'Number of Departament';

COMMENT ON COLUMN EMPLOYEE.ID_TEAM IS 'Number of Team';

COMMENT ON COLUMN EMPLOYEE.NAME IS 'Employee first name';

COMMENT ON COLUMN EMPLOYEE.SURNAME IS 'Employee second name';

COMMENT ON COLUMN EMPLOYEE.EMAIL IS 'Employee email';

COMMENT ON COLUMN EMPLOYEE.PHONE IS 'Employee private phone';

COMMENT ON COLUMN EMPLOYEE.ADRESS IS 'Employee home adress';
