CREATE TABLE ROLE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, ID_ROLE NUMBER
, ROLE VARCHAR2(100)
);

COMMENT ON COLUMN ROLE.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN ROLE.ID_ROLE IS 'Number of role';

COMMENT ON COLUMN ROLE.ROLE IS 'Role description';