DEFINE USER_NAME = &&1
DEFINE DATA_TABLESPACE = '&&USER_NAME._DATA'
DEFINE INDEX_TABLESPACE = '&&USER_NAME._IDX'

ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT PK_EMPLOYEE_ROLE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EMPLOYEE_ROLE MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE COMPATIBILITY_TABLE MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE EMPLOYEE_PROJECT ADD CONSTRAINT PK_EMPLOYEE_PROJECT PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EMPLOYEE_PROJECT MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE DEPARTMENT MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE TEAM ADD CONSTRAINT PK_TEAM PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE TEAM MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE TASK ADD CONSTRAINT PK_TASK PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE TASK MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE STATUS  ADD CONSTRAINT PK_STATUS_TASK  PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE STATUS  MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE STAGE ADD CONSTRAINT PK_STAGE  PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE STAGE MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE SKILLS ADD CONSTRAINT PK_SKILLS PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE SKILLS MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE ROLE ADD CONSTRAINT PK_ROLE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE ROLE MOVE TABLESPACE &&DATA_TABLESPACE;


ALTER TABLE EMPLOYEE ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EMPLOYEE MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE PROJECT ADD CONSTRAINT PK_PROJECT PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE PROJECT MOVE TABLESPACE &&DATA_TABLESPACE;

ALTER TABLE SKILL_EMPLOYEE  ADD CONSTRAINT PK_SKILL_EMPLOYEE  PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE SKILL_EMPLOYEE  MOVE TABLESPACE &&DATA_TABLESPACE;


ALTER TABLE EMPLOYEE_TASK ADD CONSTRAINT PK_EMPLOYEE_TASK PRIMARY KEY (ID) USING INDEX TABLESPACE &&INDEX_TABLESPACE;
ALTER TABLE EMPLOYEE_TASK MOVE TABLESPACE &&DATA_TABLESPACE;


--CREATE FOREIGN KEYS 

ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT fk_EMPLOYEE_ROLE_ID FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEE(ID) ON DELETE SET NULL;

CREATE INDEX fk_EMPLOYEE_ROLE_ID_PERSON_I ON EMPLOYEE_ROLE(EMPLOYEE_ID) TABLESPACE &&INDEX_TABLESPACE;

ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT fk_ROLE_EMPLOYEE_ID FOREIGN KEY(ROLE_ID)
REFERENCES ROLE(ID) ON DELETE SET NULL;

CREATE INDEX fk_EMPLOYEE_ROLE_ID_ROLE_I ON EMPLOYEE_ROLE(ROLE_ID) TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE EMPLOYEE_PROJECT ADD CONSTRAINT fk_EMPLOYEE_PROJECT_ID_PROJECT FOREIGN KEY(PROJECT_ID)
REFERENCES PROJECT(ID) ON DELETE SET NULL;

CREATE INDEX fk_EMPLOYEE_PROJECT_ID_PROJECT_I ON EMPLOYEE_PROJECT(PROJECT_ID) TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE EMPLOYEE_PROJECT ADD CONSTRAINT fk_EMPLOYEE_PROJECT_ID_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEE(ID) ON DELETE SET NULL;

CREATE INDEX fk_EMPLOYEE_PROJECT_ID_PERSON_I ON EMPLOYEE_PROJECT(EMPLOYEE_ID) TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE TASK ADD CONSTRAINT STAGE_ID FOREIGN KEY(STAGE_ID)
REFERENCES STAGE(ID) ON DELETE CASCADE;

CREATE INDEX fk_TASK_ID_STAGE_I ON TASK(STAGE_ID) TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE TASK ADD CONSTRAINT fk_TASK_ID_STATUS FOREIGN KEY(STATUS_ID)
REFERENCES STATUS(ID)  ON DELETE SET NULL;

CREATE INDEX fk_TASK_ID_STATUS_I ON TASK(STATUS_ID) TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE SKILL_EMPLOYEE  ADD CONSTRAINT fk_SKILL_EMPLOYEE_ID_PERSON FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEE(ID) ON DELETE SET NULL;

CREATE INDEX fk_SKILL_EMPLOYEE_ID_PERSON_I ON SKILL_EMPLOYEE(EMPLOYEE_ID) TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE SKILL_EMPLOYEE  ADD CONSTRAINT fk_SKILL_EMPLOYEE_ID_SKILL FOREIGN KEY(SKILL_ID)
REFERENCES SKILLS(ID) ON DELETE SET NULL;

CREATE INDEX fk_SKILL_EMPLOYEE_ID_SKILL_I ON SKILL_EMPLOYEE(SKILL_ID) TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE STAGE ADD CONSTRAINT fk_PROJECT_ID_STAGE FOREIGN KEY(PROJECT_ID)
REFERENCES PROJECT(ID) ON DELETE CASCADE;

CREATE INDEX fk_PROJECT_ID_STAGE_I ON STAGE(PROJECT_ID) TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE EMPLOYEE_TASK ADD CONSTRAINT fk_EMPLOYEE_TASK_ID_PERSON FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEE(ID) ON DELETE SET NULL;

CREATE INDEX fk_EMPLOYEE_TASK_ID_PERSON_I ON EMPLOYEE_TASK(EMPLOYEE_ID) TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE EMPLOYEE_TASK ADD CONSTRAINT fk_EMPLOYEE_TASK_ID_TASK FOREIGN KEY(TASK_ID)
REFERENCES TASK(ID) ;

CREATE INDEX fk_EMPLOYEE_TASK_ID_TASK_I ON EMPLOYEE_TASK(TASK_ID) TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_EMPLOYEE_ID_DEPARTMENT FOREIGN KEY(DEPARTMENT_ID)
REFERENCES DEPARTMENT(ID) ON DELETE SET NULL;

CREATE INDEX fk_EMPLOYEE_TASK_ID_DEPARTMENT_I ON EMPLOYEE(DEPARTMENT_ID) TABLESPACE &&INDEX_TABLESPACE;


ALTER TABLE TEAM ADD CONSTRAINT fk_TEAM_ID_EMPLOYEE FOREIGN KEY(EMPLOYEE_LEAD_ID)
REFERENCES EMPLOYEE(ID) ON DELETE SET NULL;

CREATE INDEX fk_TEAM_ID_EMPLOYEE_I ON TEAM(EMPLOYEE_LEAD_ID) TABLESPACE &&INDEX_TABLESPACE;


UNDEFINE USER_NAME
UNDEFINE DATA_TABLESPACE
UNDEFINE INDEX_TABLESPACE

