CREATE TABLE SKILLS (
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, ID_SKILL NUMBER
, SKILL VARCHAR2(100) 
);

COMMENT ON COLUMN SKILLS.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN SKILLS.ID_SKILL IS 'Number of skill';

COMMENT ON COLUMN SKILLS.SKILL IS 'Skill name';
