CREATE TABLE DEPARTMENT 
(
ID_DEPARTMENT NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL 
, NAME VARCHAR2(20) 
, FLOOR VARCHAR2(20) 
, DESCRIPTION VARCHAR2(100) 
);
COMMENT ON COLUMN DEPARTMENT.ID_DEPARTMENT IS 'Unique number';

COMMENT ON COLUMN DEPARTMENT.NAME IS 'Department name';

COMMENT ON COLUMN DEPARTMENT.FLOOR IS 'Department floor';

COMMENT ON COLUMN DEPARTMENT.DESCRIPTION IS 'Common description';
