CREATE TABLE EMPLOYEE_TASK (
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, ID_PERSON NUMBER 
, COLUMN2 NUMBER 
);

COMMENT ON COLUMN EMPLOYEE_TASK.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN EMPLOYEE_TASK.ID_PERSON IS 'Number of person';

COMMENT ON COLUMN EMPLOYEE_TASK.COLUMN2 IS 'Number of task';
