DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE COMPATIBILITY_TABLE 
(
  ID_ROLE INT 
, ID_INCOMPATIBLE_ROLE INT 
) TABLESPACE &&DATA_TBS_NAME&&CURS;

COMMENT ON COLUMN COMPATIBILITY_TABLE.ID_ROLE IS 'Id of the role to check';

COMMENT ON COLUMN COMPATIBILITY_TABLE.ID_INCOMPATIBLE_ROLE IS 'Id role incompatible';
