CREATE TABLE STAGE (
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, ID_STAGE NUMBER 
, NAME VARCHAR2(20) 
);

COMMENT ON COLUMN STAGE.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN STAGE.ID_STAGE IS 'Number of stage';

COMMENT ON COLUMN STAGE.NAME IS 'Name of this stage';
