DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE DEPARTMENT 
(
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL 
, NAME VARCHAR2(20) 
, FLOOR VARCHAR2(20) 
, DESCRIPTION VARCHAR2(100) 
) TABLESPACE &&DATA_TBS_NAME&&CURS;

COMMENT ON COLUMN DEPARTMENT.ID IS 'Unique number';

COMMENT ON COLUMN DEPARTMENT.NAME IS 'Department name';

COMMENT ON COLUMN DEPARTMENT.FLOOR IS 'Department floor';

COMMENT ON COLUMN DEPARTMENT.DESCRIPTION IS 'Common description';
