DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE TEAM (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, EMPLOYEE_LEAD_ID NUMBER
)TABLESPACE &&DATA_TBS_NAME&&CURS;
COMMENT ON COLUMN TEAM.ID IS 'Unique value, serves as the primary key';

COMMENT ON COLUMN TEAM.EMPLOYEE_LEAD_ID IS 'Id of lead';