DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE PROJECT(
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, NAME VARCHAR2(100) 
, DESCRIPTION VARCHAR2(100) 
, START_DAY DATE 
, END_DAY DATE 
) TABLESPACE &&DATA_TBS_NAME&&CURS;

COMMENT ON COLUMN PROJECT.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN PROJECT.NAME IS 'Name of project';

COMMENT ON COLUMN PROJECT.DESCRIPTION IS 'Description of project';

COMMENT ON COLUMN PROJECT.START_DAY IS 'Start';

COMMENT ON COLUMN PROJECT.END_DAY IS 'End';

