CREATE TABLE STATUS (
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, ID_STATUS NUMBER 
, STATUS VARCHAR2(100) 
);

COMMENT ON COLUMN STATUS.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN STATUS.ID_STATUS IS 'Number of status';

COMMENT ON COLUMN STATUS.STATUS IS 'Name of status';
