CREATE TABLE TEAM (
    ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, ID_TEAM NUMBER
, ID_PERSON NUMBER
);
COMMENT ON COLUMN TEAM.ID IS 'Unique value, serves as the primary key';

COMMENT ON COLUMN TEAM.ID_TEAM IS 'Number of team';

COMMENT ON COLUMN TEAM.ID_PERSON IS 'Id of lead';