DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE SKILL_EMPLOYEE 
(
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, EMPLOYEE_ID NUMBER 
, SKILL_ID NUMBER 
) TABLESPACE &&DATA_TBS_NAME&&CURS;


COMMENT ON COLUMN SKILL_EMPLOYEE.EMPLOYEE_ID IS 'Unique number for person';

COMMENT ON COLUMN SKILL_EMPLOYEE.SKILL_ID IS 'Number of skill';
