DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE TASK (
ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL
, NAME VARCHAR2(100) 
, STATUS_ID NUMBER 
, START_DATE DATE
, END_DATE DATE
, STAGE_ID NUMBER
) TABLESPACE &&DATA_TBS_NAME&&CURS;

COMMENT ON COLUMN TASK.ID IS 'Unique value of the primary key for the table';

COMMENT ON COLUMN TASK.STAGE_ID IS 'Fk for stage';

COMMENT ON COLUMN TASK.NAME IS 'Name of task';

COMMENT ON COLUMN TASK.STATUS_ID IS 'Number of status';

COMMENT ON COLUMN TASK.START_DATE IS 'Start of task';

COMMENT ON COLUMN TASK.END_DATE IS 'End of task';

COMMENT ON COLUMN TASK.TEAM_ID IS 'Number of team';
