PROMPT 'Drop TableSpaces'

DEFINE USER_NAME = &&1
DEFINE TBS_DATA_NAME = '&&USER_NAME._DATA'
DEFINE TBS_IDX_NAME = '&&USER_NAME._IDX'

DROP TABLESPACE &&TBS_DATA_NAME
  INCLUDING CONTENTS
    CASCADE CONSTRAINTS;
    

DROP TABLESPACE &&TBS_IDX_NAME
  INCLUDING CONTENTS
    CASCADE CONSTRAINTS;
      
PROMPT 'TableSpaces Dropped'